### ISSUE TITLE
Build instructions for the latest main branch? 

### ISSUE THREAD

**Issue by ai-and-i** [meta-flutter/rive-common#2]
Hi, thanks for the great work on getting rive-flutter to work on Linux! I'm already using it in my project. I noticed that the latest ([fcad768](https://github.com/meta-flutter/rive-common/commit/fcad7687d196e2ba64810e08374ec780c6e2bfb8)) commit to main doesn't seem to have neither build instructions not the linux-specific changes. Any plans to bring it back? Let me know if I can help in any way!

**Comment by jwinarske** [comment]
The only thing missing is the readme note.  I reference this project from meta-flutter as rive-text.  It builds and runs with the the CMakelists.txt in the repo root.  I'll update the readme.  Thanks!

**Comment by jwinarske** [comment]
README updated in https://github.com/meta-flutter/rive-common/pull/3
